### ISSUE TITLE
Gearman queue plugin fails

### ISSUE THREAD

**Issue by christophervalles** [samuel/python-munin#7]
Hi Samuel,

Yesterday I started using some of your munin plugins, thank you!

I notice that gearman_queue plugin is throwing an error and is not showing on the dashboard of munin in the other hand gearman_connections is working fine, below you can see the error message:

```
2012/05/12-12:34:20 [12171] Error output from gearman_queues:
2012/05/12-12:34:20 [12171]     Traceback (most recent call last):
2012/05/12-12:34:20 [12171]       File "/etc/munin/plugins/gearman_queues", line 40, in <module>
2012/05/12-12:34:20 [12171]         MuninGearmanQueuesPlugin().run()
2012/05/12-12:34:20 [12171]       File "/etc/munin/plugins/gearman_queues", line 15, in __init__
2012/05/12-12:34:20 [12171]         self.queues = os.environ['GEARMAN_QUEUES'].split(',')
2012/05/12-12:34:20 [12171]       File "/usr/lib/python2.6/UserDict.py", line 22, in __getitem__
2012/05/12-12:34:20 [12171]         raise KeyError(key)
2012/05/12-12:34:20 [12171]     KeyError: 'GEARMAN_QUEUES'
```

How can I fix it? I forgot to configure something?

King regards

**Comment by samuel** [comment]
You need to add a config file to /etc/munin/plugin-conf.d/gearman  (on Ubuntu, other distros may vary the path)

with the content:

[gearman*]
env.GEARMAN_QUEUES somequeue,otherqueue

You can create multiple links to the same plugin and give them different arguments by chaging the [gearman*] to be specific.. like

[gearman_somequeue]
env.GEARMAN_QUEUES somequeue

then ln -s gearman_queues gearman_somequeue

**Comment by christophervalles** [comment]
Hi Samuel,

Works like a charm.

Thank you for your response and those awesome plugins :)

King regards
